version: "3.9"
services:
  # ===================================================================
  # POSTGRES SERVER
  # ===================================================================
  postgres:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5433:5432
    volumes:
      - ./docker/data/postgresql:/var/lib/postgresql/data
    networks:
      - dev-network

  # ===================================================================
  # PGADMIN SERVER
  # ===================================================================
  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
